    <#
.SYNOPSIS
    Codex CLI Installation and Configuration Script (v3.0)

.DESCRIPTION
    Installs Codex CLI and properly configures auth.json and config.toml
    - Saves auth.json with UTF-8 WITHOUT BOM
    - Creates config.toml if it doesn't exist
    All prompts and messages are in English.

.NOTES
    Author: Claude Code Assistant
    Date: 2026-04-01
    Version: 3.0.0
    Changes:
      - Fixed UTF-8 BOM issue (uses UTF-8 without BOM)
      - Auto-generates config.toml if missing
#>

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$ErrorActionPreference = "Stop"

function Write-Header {
    param([string]$Title)
    Write-Host ""
    Write-Host ("=" * 70)
    Write-Host "  $Title"
    Write-Host ("=" * 70)
}

function Write-Step {
    param(
        [int]$Number,
        [int]$Total,
        [string]$Description
    )
    Write-Host "[$Number/$Total] $Description..." -ForegroundColor Cyan
}

function Test-Command {
    param([string]$Command)
    $null = Get-Command $Command -ErrorAction SilentlyContinue
    return $?
}

function Save-TokenToCodex {
    param([string]$Token)

    # Get Codex configuration directory
    $codexDir = Join-Path $env:USERPROFILE ".codex"
    $authFile = Join-Path $codexDir "auth.json"

    # Create directory if it doesn't exist
    if (-not (Test-Path $codexDir)) {
        Write-Host "Creating Codex config directory: $codexDir" -ForegroundColor Green
        New-Item -ItemType Directory -Path $codexDir -Force | Out-Null
    }

    # Backup existing auth.json if it exists
    if (Test-Path $authFile) {
        $backupFile = Join-Path $codexDir "auth.json.backup"
        Write-Host "Backing up existing auth.json to: $backupFile" -ForegroundColor Yellow
        Copy-Item $authFile $backupFile -Force
    }

    # Create auth data
    $authData = @{
        OPENAI_API_KEY = $Token
    }

    # Save to auth.json with UTF-8 WITHOUT BOM
    try {
        $authJson = $authData | ConvertTo-Json

        # Use UTF-8 without BOM (critical fix!)
        $utf8NoBom = New-Object System.Text.UTF8Encoding $false
        [System.IO.File]::WriteAllText($authFile, $authJson, $utf8NoBom)

        Write-Host ""
        Write-Host "✅ Token saved to: $authFile" -ForegroundColor Green
        Write-Host "   Encoding: UTF-8 without BOM (correct format)" -ForegroundColor Gray

        # Verify no BOM
        $bytes = [System.IO.File]::ReadAllBytes($authFile)
        $hasBOM = ($bytes.Length -ge 3) -and ($bytes[0] -eq 0xEF) -and ($bytes[1] -eq 0xBB) -and ($bytes[2] -eq 0xBF)

        if ($hasBOM) {
            Write-Host "❌ Warning: File has BOM (should not happen)" -ForegroundColor Red
            return $false
        } else {
            Write-Host "✅ Verified: No BOM in file" -ForegroundColor Green
        }

        return $true

    } catch {
        Write-Host ""
        Write-Host "❌ Error: Could not save token: $_" -ForegroundColor Red
        return $false
    }
}

function Create-ConfigToml {
    param([string]$ApiBaseUrl = "https://new-api.300666.cn/v1")

    $codexDir = Join-Path $env:USERPROFILE ".codex"
    $configFile = Join-Path $codexDir "config.toml"

    # Check if config already exists
    if (Test-Path $configFile) {
        Write-Host ""
        Write-Host "Config file already exists: $configFile" -ForegroundColor Yellow
        Write-Host "Skipping config creation" -ForegroundColor Yellow
        return $true
    }

    # Create default config.toml
    Write-Host ""
    Write-Host "Creating default config.toml..." -ForegroundColor Cyan

    $configContent = @"
# Codex CLI Configuration
# Generated by install script on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

model = "gpt-5.3-codex"
model_provider = "custom"
model_reasoning_effort = "medium"
disable_response_storage = true
preferred_auth_method = "apikey"
rmcp_client = true

[model_providers.custom]
name = "custom"
base_url = "$ApiBaseUrl"
wire_api = "responses"
requires_openai_auth = true

[notice]
hide_full_access_warning = true

[windows]
sandbox = "unelevated"
"@

    try {
        # Save with UTF-8 without BOM
        $utf8NoBom = New-Object System.Text.UTF8Encoding $false
        [System.IO.File]::WriteAllText($configFile, $configContent, $utf8NoBom)

        Write-Host "✅ Config created: $configFile" -ForegroundColor Green
        return $true

    } catch {
        Write-Host "❌ Error: Could not create config: $_" -ForegroundColor Red
        return $false
    }
}

function Test-CodexLogin {
    Write-Host ""
    Write-Host "Testing Codex authentication..." -ForegroundColor Cyan

    try {
        $result = & codex login status 2>&1

        if ($LASTEXITCODE -eq 0) {
            Write-Host ""
            Write-Host "✅ Codex authentication successful!" -ForegroundColor Green
            Write-Host "$result" -ForegroundColor Gray
            return $true
        } else {
            Write-Host ""
            Write-Host "⚠️  Codex login check returned non-zero exit code" -ForegroundColor Yellow
            return $false
        }

    } catch {
        Write-Host ""
        Write-Host "⚠️  Could not test Codex login: $_" -ForegroundColor Yellow
        return $false
    }
}

# Main installation flow
try {
    Write-Header "Codex CLI Installation and Configuration"

    $totalSteps = 6

    # Step 1: Check Node.js
    Write-Step 1 $totalSteps "Checking Node.js"
    if (Test-Command "node") {
        $nodeVersion = node --version
        Write-Host "+ Node.js $nodeVersion detected (>= 16.0 required)" -ForegroundColor Green
        Write-Host "Skipping Node.js installation" -ForegroundColor Yellow
    } else {
        Write-Host "- Node.js not found" -ForegroundColor Red
        Write-Host "Please install Node.js from: https://nodejs.org/" -ForegroundColor Yellow
        exit 1
    }

    # Step 2: Check Git
    Write-Step 2 $totalSteps "Checking Git"
    if (Test-Command "git") {
        $gitVersion = git --version
        Write-Host "+ $gitVersion detected" -ForegroundColor Green
        Write-Host "Skipping Git installation" -ForegroundColor Yellow
    } else {
        Write-Host "- Git not found" -ForegroundColor Red
        Write-Host "Please install Git from: https://git-scm.com/" -ForegroundColor Yellow
        exit 1
    }

    # Step 3: Check Codex CLI
    Write-Step 3 $totalSteps "Checking Codex CLI"
    if (Test-Command "codex") {
        try {
            $codexVersion = & codex --version 2>$null
            Write-Host "+ Codex CLI detected" -ForegroundColor Green
        } catch {
            Write-Host "+ Codex CLI detected" -ForegroundColor Green
        }
        Write-Host "Skipping Codex installation" -ForegroundColor Yellow
    } else {
        Write-Host "- Codex CLI not found" -ForegroundColor Red
        Write-Host "Please install Codex CLI first" -ForegroundColor Yellow
        Write-Host "Visit: https://docs.codex.anthropic.com/installation" -ForegroundColor Yellow
        exit 1
    }

    # Step 4: Configure API token
    Write-Step 4 $totalSteps "Configuring API Token"

    Write-Header "API Token Setup"

    Write-Host ""
    Write-Host "Please follow these steps to get your API token:" -ForegroundColor White
    Write-Host "  1. Visit: https://new-api.300666.cn/" -ForegroundColor White
    Write-Host "  2. Login with DingTalk" -ForegroundColor White
    Write-Host "  3. Navigate to: Token Binding -> Add Token" -ForegroundColor White
    Write-Host "  4. Copy the generated token" -ForegroundColor White
    Write-Host ""

    # Prompt for token (securely)
    $secureToken = Read-Host "Enter your API token (input will be hidden)" -AsSecureString
    $token = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureToken)
    )

    # Validate token
    if ([string]::IsNullOrWhiteSpace($token)) {
        Write-Host ""
        Write-Host "❌ Error: Token cannot be empty!" -ForegroundColor Red
        exit 1
    }

    if ($token.Length -lt 10) {
        Write-Host ""
        Write-Host "❌ Error: Token is too short. Please check if it's complete." -ForegroundColor Red
        exit 1
    }

    # Warning if token doesn't start with sk-
    if (-not $token.StartsWith("sk-")) {
        Write-Host ""
        Write-Host "⚠️  Warning: Token doesn't start with 'sk-'" -ForegroundColor Yellow
        Write-Host "This may not be a valid OpenAI-compatible token" -ForegroundColor Yellow
        $confirm = Read-Host "Continue anyway? (y/N)"
        if ($confirm -ne 'y' -and $confirm -ne 'Y') {
            Write-Host "Installation cancelled by user." -ForegroundColor Yellow
            exit 0
        }
    }

    Write-Host ""
    Write-Host "✅ Token format validated successfully" -ForegroundColor Green

    # Save token to Codex auth.json
    if (-not (Save-TokenToCodex $token)) {
        exit 1
    }

    # Step 5: Create config.toml
    Write-Step 5 $totalSteps "Creating Configuration File"

    $apiBaseUrl = "https://new-api.300666.cn/v1"
    if (-not (Create-ConfigToml $apiBaseUrl)) {
        Write-Host "⚠️  Warning: Could not create config.toml" -ForegroundColor Yellow
        Write-Host "Codex may create it automatically on first run" -ForegroundColor Yellow
    }

    # Step 6: Verify configuration
    Write-Step 6 $totalSteps "Verifying Configuration"

    Test-CodexLogin | Out-Null

    # Final success message
    Write-Header "Installation Complete"

    Write-Host ""
    Write-Host "✅ Codex CLI configured successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "Configuration summary:" -ForegroundColor Cyan
    Write-Host "  Auth file:   $env:USERPROFILE\.codex\auth.json" -ForegroundColor Gray
    Write-Host "  Config file: $env:USERPROFILE\.codex\config.toml" -ForegroundColor Gray
    Write-Host "  Encoding:    UTF-8 without BOM (correct)" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Cyan
    Write-Host "  1. Open a new terminal (to reload environment)" -ForegroundColor White
    Write-Host "  2. Run: codex" -ForegroundColor White
    Write-Host "  3. If you see a login prompt, just press ENTER" -ForegroundColor White
    Write-Host "     (Your API key is already configured)" -ForegroundColor White
    Write-Host ""
    Write-Host "Enjoy using Codex CLI! 🚀" -ForegroundColor Green
    Write-Host ""

} catch {
    Write-Host ""
    Write-Host "❌ Installation failed: $_" -ForegroundColor Red
    Write-Host ""
    Write-Host "Stack trace:" -ForegroundColor Yellow
    Write-Host $_.ScriptStackTrace -ForegroundColor Gray
    exit 1
}